name: bytecare_mobile
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For Icons on iOS.
  cupertino_icons: ^0.1.3

  # UI Modules
  google_fonts: ^1.1.1
  ms_undraw: ^2.2.0+15
  im_stepper: ^0.1.2+8
  flutter_spinkit: ^4.1.2+1
  wave: ^0.1.0

  # Functionality Modules
  http: ^0.12.2
  form_field_validator: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true